TMPL = """
jobs:
    test-docker-ci-{sys}:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   run: sudo apt-get update -qq
        -   run: sudo apt-get -y remove libgd3 libunwind-14 nginx
        -   run: sudo apt-get --no-install-recommends install -y eatmydata
        -   run: sudo eatmydata apt-get --no-install-recommends install
                 -y build-essential
                cpanminus libperl-dev libxml2-dev
                libxslt1-dev perl xz-utils zip
        -   run: sudo cpanm --verbose Carp Carp::Always
                Docker::CLI::Wrapper::Container
                Moo Path::Tiny
        -   run: perl CI-testing/docker-ci-run.pl --regex-filter='{sysregex}'
                --cleanrun
        timeout-minutes: 20
name: test-docker-ci-{sys}
'on':
- push
"""

for rec in [{'dist': "debian", }, {'dist': "fedora", }, ]:
    dist = rec['dist']
    outs = TMPL.format(sys=dist, sysregex=dist)
    with open(".github/workflows/test-docker-ci-{sys}.yml".format(sys=dist),
              "wt") as fh:
        fh.write("# This file is GENERATED BY {}\n".format(
            "CI-testing/generate_gh_actions.py"))
        fh.write(outs)
